#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""生成深圳训练配置(configs/深圳/)。

biases/scales 来自全量 8928 样本统计(2026-08-25,scripts/compute_stats_sz.py)。
用法(本地执行):
  python scripts/generate_sz_configs.py
"""
import os

# ---- 全量统计(52 个变量,不含 swdown——仅用于昼夜过滤,不作输入) ----
BIASES = {
    "hfx": 49.273806, "hr_u_ml0": 0.623149, "hr_u_ml1": 0.807892,
    "hr_u_ml10": 1.816318, "hr_u_ml2": 0.950596, "hr_u_ml3": 1.076708,
    "hr_u_ml5": 1.302711, "hr_v_ml0": 5.253592, "hr_v_ml1": 6.141717,
    "hr_v_ml10": 7.226114, "hr_v_ml2": 6.590166, "hr_v_ml3": 6.868257,
    "hr_v_ml5": 7.178925, "hr_w_ml0": -0.006146, "hr_w_ml1": -0.009084,
    "hr_w_ml10": -0.006466, "hr_w_ml2": -0.010560, "hr_w_ml3": -0.010972,
    "hr_w_ml5": -0.010424, "lh": 103.911887, "lr_hfx": 49.268623,
    "lr_lh": 103.904759, "lr_lu": 13.291667, "lr_pblh": 439.768384,
    "lr_psfc": 100146.628628, "lr_t2": 302.363539, "lr_tsk": 303.673694,
    "lr_u_ml0": 0.623028, "lr_u_ml1": 0.807750, "lr_u_ml10": 1.816326,
    "lr_u_ml2": 0.950459, "lr_u_ml3": 1.076595, "lr_u_ml5": 1.302655,
    "lr_v_ml0": 5.254021, "lr_v_ml1": 6.142045, "lr_v_ml10": 7.226163,
    "lr_v_ml2": 6.590432, "lr_v_ml3": 6.868482, "lr_v_ml5": 7.179089,
    "lr_w_ml0": -0.006150, "lr_w_ml1": -0.009088, "lr_w_ml10": -0.006468,
    "lr_w_ml2": -0.010564, "lr_w_ml3": -0.010976, "lr_w_ml5": -0.010428,
    "lr_z": 46.932178, "lu": 13.271856, "pblh": 439.823726,
    "psfc": 100146.512990, "t2": 302.363593, "tsk": 303.673830,
    "z": 46.942367,
}
SCALES = {
    "hfx": 109.494270, "hr_u_ml0": 3.201259, "hr_u_ml1": 3.626610,
    "hr_u_ml10": 4.760493, "hr_u_ml2": 3.843873, "hr_u_ml3": 3.991688,
    "hr_u_ml5": 4.219769, "hr_v_ml0": 3.015156, "hr_v_ml1": 3.278939,
    "hr_v_ml10": 3.661751, "hr_v_ml2": 3.419784, "hr_v_ml3": 3.502157,
    "hr_v_ml5": 3.596125, "hr_w_ml0": 0.176552, "hr_w_ml1": 0.227139,
    "hr_w_ml10": 0.285809, "hr_w_ml2": 0.249182, "hr_w_ml3": 0.262110,
    "hr_w_ml5": 0.278466, "lh": 115.019579, "lr_hfx": 96.056261,
    "lr_lh": 100.098612, "lr_lu": 4.841665, "lr_pblh": 259.373389,
    "lr_psfc": 851.978881, "lr_t2": 1.812234, "lr_tsk": 4.072291,
    "lr_u_ml0": 3.156910, "lr_u_ml1": 3.591444, "lr_u_ml10": 4.748498,
    "lr_u_ml2": 3.816240, "lr_u_ml3": 3.969457, "lr_u_ml5": 4.203966,
    "lr_v_ml0": 2.939741, "lr_v_ml1": 3.211942, "lr_v_ml10": 3.640043,
    "lr_v_ml2": 3.363114, "lr_v_ml3": 3.454182, "lr_v_ml5": 3.561363,
    "lr_w_ml0": 0.094738, "lr_w_ml1": 0.120013, "lr_w_ml10": 0.154744,
    "lr_w_ml2": 0.132530, "lr_w_ml3": 0.139346, "lr_w_ml5": 0.147888,
    "lr_z": 74.091197, "lu": 4.821964, "pblh": 286.327771,
    "psfc": 969.949536, "t2": 1.893462, "tsk": 4.427874,
    "z": 85.115224,
}

WIND_HR = [
    "hr_u_ml0", "hr_v_ml0", "hr_w_ml0", "hr_u_ml1", "hr_v_ml1", "hr_w_ml1",
    "hr_u_ml2", "hr_v_ml2", "hr_w_ml2", "hr_u_ml3", "hr_v_ml3", "hr_w_ml3",
    "hr_u_ml5", "hr_v_ml5", "hr_w_ml5", "hr_u_ml10", "hr_v_ml10", "hr_w_ml10",
]
WIND_LR = [
    "lr_u_ml0", "lr_v_ml0", "lr_w_ml0", "lr_u_ml1", "lr_v_ml1", "lr_w_ml1",
    "lr_u_ml2", "lr_v_ml2", "lr_w_ml2", "lr_u_ml3", "lr_v_ml3", "lr_w_ml3",
    "lr_u_ml5", "lr_v_ml5", "lr_w_ml5", "lr_u_ml10", "lr_v_ml10", "lr_w_ml10",
]
COND_HR = ["t2", "z", "lu", "tsk", "hfx", "lh", "psfc", "pblh"]
COND_LR = ["lr_t2", "lr_z", "lr_lu", "lr_tsk", "lr_hfx", "lr_lh", "lr_psfc", "lr_pblh"]
CHANNEL_WEIGHTS = [1, 1, 10] * 6  # W 分量加权


def yaml_lines(indent, key, value):
    pad = " " * indent
    if isinstance(value, list):
        lines = ["{}{}:".format(pad, key)]
        for v in value:
            lines.append("{}  - {}".format(pad, v))
        return lines
    if isinstance(value, dict):
        lines = ["{}{}:".format(pad, key)]
        for k, v in value.items():
            lines.append("{}  {}: {}".format(pad, k, v))
        return lines
    if value is None:
        return ["{}{}: null".format(pad, key)]
    if isinstance(value, bool):
        return ["{}{}: {}".format(pad, key, str(value).lower())]
    return ["{}{}: {}".format(pad, key, value)]


def build_config(inner_channel, epochs, conditions, day_night,
                 divergence_weight, vorticity_weight, batch_size,
                 patience, name_suffix):
    # UNet forward 为 torch.cat([yt, y_cond], dim=1):
    # in_channel = yt(18 LR wind) + y_cond(18 LR wind + 8 cond) = 44
    # (香港 in_channel=28 = 18 + 10 同理;交接指南写的 26 有误)
    in_channel = len(WIND_LR) + len(WIND_LR) + len(conditions)
    lines = []
    lines.append("# Shenzhen config generated by scripts/generate_sz_configs.py")
    lines.append("# in_channel=%d (%d LR wind + %d cond), day_night=%s, "
                 "div=%.2f vort=%.2f" % (in_channel, len(WIND_LR), len(conditions),
                                         day_night, divergence_weight, vorticity_weight))
    lines.append("data:")
    lines.append("  biases:")
    for k in sorted(BIASES):
        lines.append("    {}: {:.6f}".format(k, BIASES[k]))
    lines.append("  scales:")
    for k in sorted(SCALES):
        lines.append("    {}: {:.6f}".format(k, SCALES[k]))
    lines.extend(yaml_lines(2, "discarded_minute_range", [1, 30]))
    lines.extend(yaml_lines(2, "dtype", "float32"))
    lines.extend(yaml_lines(2, "hr_cropped_shape", [96, 112]))
    lines.extend(yaml_lines(2, "hr_data_shape", [96, 112]))
    lines.extend(yaml_lines(2, "input_variable_names", WIND_LR + conditions))
    lines.extend(yaml_lines(2, "is_clipped", False))
    lines.extend(yaml_lines(2, "max_clipped_value", None))
    lines.extend(yaml_lines(2, "min_clipped_value", None))
    lines.extend(yaml_lines(2, "missing_value", 0.0))
    lines.extend(yaml_lines(2, "target_variable_names", WIND_HR))
    lines.extend(yaml_lines(2, "day_night_filter", day_night))
    lines.append("loader:")
    lines.extend(yaml_lines(2, "batch_size", batch_size))
    lines.extend(yaml_lines(2, "dl_data_ver", "wrf_3d_v1_sz"))
    lines.extend(yaml_lines(2, "num_workers", 4))
    lines.extend(yaml_lines(2, "seed", 42))
    lines.extend(yaml_lines(2, "train_valid_test_ratios", [0.7, 0.145, 0.155]))
    lines.append("model:")
    lines.extend(yaml_lines(2, "attn_res", [16]))
    lines.extend(yaml_lines(2, "channel_mults", [1, 2, 4, 8, 8]))
    lines.extend(yaml_lines(2, "channels_each_head", 16))
    lines.extend(yaml_lines(2, "dropout", 0.2))
    lines.extend(yaml_lines(2, "in_channel", in_channel))
    lines.extend(yaml_lines(2, "inner_channel", inner_channel))
    lines.extend(yaml_lines(2, "max_period", 10.0))
    lines.extend(yaml_lines(2, "out_channel", 18))
    lines.extend(yaml_lines(2, "res_blocks", 1))
    lines.extend(yaml_lines(2, "resblock_updown", True))
    lines.append("si:")
    lines.extend(yaml_lines(2, "eps", 0.2))
    lines.extend(yaml_lines(2, "formula", "quadratic"))
    lines.extend(yaml_lines(2, "loss_type", "L2"))
    lines.extend(yaml_lines(2, "n_timestep", 10))
    lines.extend(yaml_lines(2, "channel_weights", CHANNEL_WEIGHTS))
    lines.extend(yaml_lines(2, "divergence_weight", divergence_weight))
    lines.extend(yaml_lines(2, "vorticity_weight", vorticity_weight))
    lines.append("train:")
    lines.extend(yaml_lines(2, "early_stopping_patience", patience))
    lines.extend(yaml_lines(2, "ema_decay", None))
    lines.extend(yaml_lines(2, "epochs", epochs))
    lines.extend(yaml_lines(2, "learning_rate", 0.0005))
    lines.append("  loss:")
    lines.extend(yaml_lines(4, "loss_name", "L2"))
    lines.extend(yaml_lines(2, "optim_name", "AdamW"))
    lines.extend(yaml_lines(2, "save_interval", 100))
    lines.extend(yaml_lines(2, "seed", 78268))
    lines.extend(yaml_lines(2, "use_amp", False))
    return "\n".join(lines) + "\n"


def main():
    out_dir = "configs/深圳"
    os.makedirs(out_dir, exist_ok=True)

    configs = {
        # 冒烟测试: 64ch, 50 epochs, 快速跑通管线
        "config_wind_3d_sz_smoke.yml": build_config(
            64, 50, COND_HR, "all", 0.0, 0.0, 2, 50, "smoke"),
        # Baseline: 128ch (~19M), 纯 L2, 无物理约束
        "config_wind_3d_sz_baseline.yml": build_config(
            128, 300, COND_HR, "all", 0.0, 0.0, 8, 300, "baseline"),
        # LR-cond: 全低精度条件输入(部署真实场景)
        "config_wind_3d_sz_lrcond.yml": build_config(
            128, 300, COND_LR, "all", 0.0, 0.0, 8, 300, "lrcond"),
        # 昼夜消融: 白天
        "config_wind_3d_sz_day.yml": build_config(
            128, 300, COND_HR, "day", 0.0, 0.0, 8, 300, "day"),
        # 昼夜消融: 夜间
        "config_wind_3d_sz_night.yml": build_config(
            128, 300, COND_HR, "night", 0.0, 0.0, 8, 300, "night"),
        # PINN: 运动学约束(3D 散度 + 大尺度涡度)
        "config_wind_3d_sz_pinn.yml": build_config(
            128, 300, COND_HR, "all", 0.1, 0.05, 8, 300, "pinn"),
    }
    for fname, content in configs.items():
        path = os.path.join(out_dir, fname)
        with open(path, "w") as f:
            f.write(content)
        print("written: {}".format(path))


if __name__ == "__main__":
    main()
